### ISSUE TITLE
how to use telemetry-agent

### ISSUE THREAD

**Issue by jkwebster** [ryankennedy/telemetry#1]
Hi,I have run telemetry-service and telemetry-example well,but would you please tell me how to use telemetry-agent in a web app?
Thaks

**Comment by ryankennedy** [comment]
Build the agent JAR file and pass it as a command line argument to the JVM using the `-javaagent` parameter.

For what it's worth, this is a mostly dormant codebase that started as a side project before being promoted to an official (yet now similarly dormant) [codebase at Yammer](https://github.com/yammer/telemetry). That fork (not a literal github fork) of the code is a bit more up to date with some fixes and changes.

**Comment by jkwebster** [comment]
Thanks much!
But for that official version,I wanna run telemetry-example,but the "telemetry.log" is empty,and there is also no database action when I type "http://localhost:8080/delayed/start/55/duration/66",would you please tell me what's wrong with it?
PS，my command is : java -javaagent:telemetry-agent-0.0.3-SNAPSHOT.jar=/Users/projs/telemetry-example/telemetry.yml -jar target/telemetry-example-0.0.3-SNAPSHOT.jar server example.yml.
